var namespacecnl =
[
    [ "add_signedness", "structcnl_1_1add__signedness.html", null ],
    [ "constant", "structcnl_1_1constant.html", null ],
    [ "custom_operator", "structcnl_1_1custom__operator.html", null ],
    [ "custom_operator< _impl::convert_op, operand< Input, _impl::native_tag >, operand< scaled_integer< ResultRep, power< ResultExponent, ResultRadix > >, neg_inf_rounding_tag > >", "structcnl_1_1custom__operator_3_01__impl_1_1convert__op_00_01operand_3_01Input_00_01__impl_1_1na5568e51aa19644f7db9813056a102c28.html", null ],
    [ "custom_operator< _impl::convert_op, operand< Input, _impl::native_tag >, operand< scaled_integer< ResultRep, power< ResultExponent, ResultRadix > >, tie_to_pos_inf_rounding_tag > >", "structcnl_1_1custom__operator_3_01__impl_1_1convert__op_00_01operand_3_01Input_00_01__impl_1_1nafaf0828809a226305068ce6baf9b4218.html", null ],
    [ "custom_operator< _impl::convert_op, operand< Input, nearest_rounding_tag >, operand< Result, power< 0, Radix > > >", "structcnl_1_1custom__operator_3_01__impl_1_1convert__op_00_01operand_3_01Input_00_01nearest__rou9de6e8f00308290e1cc88c6d11c60cf7.html", null ],
    [ "elastic_integer", "classcnl_1_1elastic__integer.html", "classcnl_1_1elastic__integer" ],
    [ "fraction", "structcnl_1_1fraction.html", "structcnl_1_1fraction" ],
    [ "from_rep", "structcnl_1_1from__rep.html", null ],
    [ "from_rep< Number, Rep >", "structcnl_1_1from__rep_3_01Number_00_01Rep_01_4.html", null ],
    [ "from_rep< scaled_integer< ArchetypeRep, power< Exponent, Radix > >, Rep >", "structcnl_1_1from__rep_3_01scaled__integer_3_01ArchetypeRep_00_01power_3_01Exponent_00_01Radix_01_4_01_4_00_01Rep_01_4.html", "structcnl_1_1from__rep_3_01scaled__integer_3_01ArchetypeRep_00_01power_3_01Exponent_00_01Radix_01_4_01_4_00_01Rep_01_4" ],
    [ "native_overflow_tag", "structcnl_1_1native__overflow__tag.html", null ],
    [ "native_rounding_tag", "structcnl_1_1native__rounding__tag.html", null ],
    [ "nearest_rounding_tag", "structcnl_1_1nearest__rounding__tag.html", null ],
    [ "neg_inf_rounding_tag", "structcnl_1_1neg__inf__rounding__tag.html", null ],
    [ "operand", "classcnl_1_1operand.html", null ],
    [ "remove_signedness", "structcnl_1_1remove__signedness.html", null ],
    [ "rep_of", "structcnl_1_1rep__of.html", null ],
    [ "rep_of< elastic_integer< Digits, Narrowest > >", "structcnl_1_1rep__of_3_01elastic__integer_3_01Digits_00_01Narrowest_01_4_01_4.html", null ],
    [ "rounding", "structcnl_1_1rounding.html", null ],
    [ "saturated_overflow_tag", "structcnl_1_1saturated__overflow__tag.html", null ],
    [ "scaled_integer", "classcnl_1_1scaled__integer.html", "classcnl_1_1scaled__integer" ],
    [ "set_digits", "structcnl_1_1set__digits.html", null ],
    [ "set_rep", "structcnl_1_1set__rep.html", null ],
    [ "set_rep< elastic_integer< Digits, Narrowest >, Rep >", "structcnl_1_1set__rep_3_01elastic__integer_3_01Digits_00_01Narrowest_01_4_00_01Rep_01_4.html", null ],
    [ "set_rounding", "structcnl_1_1set__rounding.html", null ],
    [ "set_tag", "structcnl_1_1set__tag.html", null ],
    [ "set_tag< elastic_integer< Digits, Narrowest >, elastic_tag< NewDigits, NewNarrowest > >", "structcnl_1_1set__tag_3_01elastic__integer_3_01Digits_00_01Narrowest_01_4_00_01elastic__tag_3_01eca908aaceb0293338c01a8e00181522.html", null ],
    [ "tag_of", "structcnl_1_1tag__of.html", null ],
    [ "tag_of< elastic_integer< Digits, Narrowest > >", "structcnl_1_1tag__of_3_01elastic__integer_3_01Digits_00_01Narrowest_01_4_01_4.html", null ],
    [ "throwing_overflow_tag", "structcnl_1_1throwing__overflow__tag.html", null ],
    [ "tie_to_pos_inf_rounding_tag", "structcnl_1_1tie__to__pos__inf__rounding__tag.html", null ],
    [ "to_rep", "structcnl_1_1to__rep.html", null ],
    [ "trapping_overflow_tag", "structcnl_1_1trapping__overflow__tag.html", null ],
    [ "undefined_overflow_tag", "structcnl_1_1undefined__overflow__tag.html", null ]
];